server:
  port: 443
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:54329/qpm
    username: qpm
    password: MAC0385mac
  profiles:
    active: dev